name: dart_tool_kit
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/syedmehtabali/dart_tool_kit
repository: https://github.com/syedmehtabali/dart_tool_kit
issue_tracker: https://github.com/syedmehtabali/dart_tool_kit/issues

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

